// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureStaticWebsite
{
    [AzureStaticWebsiteResourceType("azure-static-website:index:Website")]
    public partial class Website : Pulumi.ComponentResource
    {
        /// <summary>
        /// The CDN hostname of the website.
        /// </summary>
        [Output("cdnHostname")]
        public Output<string?> CdnHostname { get; private set; } = null!;

        /// <summary>
        /// The CDN URL of the website.
        /// </summary>
        [Output("cdnURL")]
        public Output<string?> CdnURL { get; private set; } = null!;

        /// <summary>
        /// The custom-domain URL of the website.
        /// </summary>
        [Output("domainURL")]
        public Output<string?> DomainURL { get; private set; } = null!;

        /// <summary>
        /// The hostname of the origin.
        /// </summary>
        [Output("originHostname")]
        public Output<string> OriginHostname { get; private set; } = null!;

        /// <summary>
        /// The direct URL of the website.
        /// </summary>
        [Output("originURL")]
        public Output<string> OriginURL { get; private set; } = null!;

        /// <summary>
        /// The name of the created resource group.
        /// </summary>
        [Output("resourceGroupName")]
        public Output<string> ResourceGroupName { get; private set; } = null!;


        /// <summary>
        /// Create a Website resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Website(string name, WebsiteArgs args, ComponentResourceOptions? options = null)
            : base("azure-static-website:index:Website", name, args ?? new WebsiteArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class WebsiteArgs : Pulumi.ResourceArgs
    {
        [Input("cdn")]
        public InputUnion<bool, Inputs.WebsiteCDNConfigArgs>? Cdn { get; set; }

        /// <summary>
        /// The domain configuration of the website.
        /// </summary>
        [Input("domain")]
        public Input<Inputs.WebsiteDomainConfigArgs>? Domain { get; set; }

        /// <summary>
        /// The default error page for the website. Defaults to error.html.
        /// </summary>
        [Input("errorDoc")]
        public Input<string>? ErrorDoc { get; set; }

        /// <summary>
        /// The default document for the site. Defaults to index.html.
        /// </summary>
        [Input("indexDoc")]
        public Input<string>? IndexDoc { get; set; }

        /// <summary>
        /// The root directory containing contents of the built website contents.
        /// </summary>
        [Input("sitePath", required: true)]
        public Input<string> SitePath { get; set; } = null!;

        /// <summary>
        /// The storage configuration of the website.
        /// </summary>
        [Input("storage")]
        public Input<Inputs.WebsiteStorageConfigArgs>? Storage { get; set; }

        public WebsiteArgs()
        {
        }
    }
}
