// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureStaticWebsite.Inputs
{

    public sealed class WebsiteStorageConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The custom domain to use for CNAME records. For example, `www.example.com`.
        /// </summary>
        [Input("customDomain")]
        public Input<string>? CustomDomain { get; set; }

        /// <summary>
        /// Whether to restrict traffic to HTTPS only. Defaults to false.
        /// </summary>
        [Input("enableHttpsTrafficOnly")]
        public Input<bool>? EnableHttpsTrafficOnly { get; set; }

        public WebsiteStorageConfigArgs()
        {
        }
    }
}
