// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureStaticWebsite.Inputs
{

    public sealed class WebsiteDomainConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The domain name of the website -- e.g., `example.com` in `www.example.com`
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The name of the Azure resource group containing the DNS zone
        /// </summary>
        [Input("resourceGroupName")]
        public Input<string>? ResourceGroupName { get; set; }

        /// <summary>
        /// The subdomain name of the website -- e.g., `www` in `www.example.com`
        /// </summary>
        [Input("subdomain", required: true)]
        public Input<string> Subdomain { get; set; } = null!;

        public WebsiteDomainConfigArgs()
        {
        }
    }
}
