// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class Website extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'azure-static-website:index:Website';

    /**
     * Returns true if the given object is an instance of Website.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Website {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Website.__pulumiType;
    }

    /**
     * The CDN hostname of the website.
     */
    public /*out*/ readonly cdnHostname!: pulumi.Output<string | undefined>;
    /**
     * The CDN URL of the website.
     */
    public /*out*/ readonly cdnURL!: pulumi.Output<string | undefined>;
    /**
     * The custom-domain URL of the website.
     */
    public /*out*/ readonly domainURL!: pulumi.Output<string | undefined>;
    /**
     * The hostname of the origin.
     */
    public /*out*/ readonly originHostname!: pulumi.Output<string>;
    /**
     * The direct URL of the website.
     */
    public /*out*/ readonly originURL!: pulumi.Output<string>;
    /**
     * The name of the created resource group.
     */
    public /*out*/ readonly resourceGroupName!: pulumi.Output<string>;

    /**
     * Create a Website resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebsiteArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.sitePath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sitePath'");
            }
            resourceInputs["cdn"] = args ? args.cdn : undefined;
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["errorDoc"] = args ? args.errorDoc : undefined;
            resourceInputs["indexDoc"] = args ? args.indexDoc : undefined;
            resourceInputs["sitePath"] = args ? args.sitePath : undefined;
            resourceInputs["storage"] = args ? args.storage : undefined;
            resourceInputs["cdnHostname"] = undefined /*out*/;
            resourceInputs["cdnURL"] = undefined /*out*/;
            resourceInputs["domainURL"] = undefined /*out*/;
            resourceInputs["originHostname"] = undefined /*out*/;
            resourceInputs["originURL"] = undefined /*out*/;
            resourceInputs["resourceGroupName"] = undefined /*out*/;
        } else {
            resourceInputs["cdnHostname"] = undefined /*out*/;
            resourceInputs["cdnURL"] = undefined /*out*/;
            resourceInputs["domainURL"] = undefined /*out*/;
            resourceInputs["originHostname"] = undefined /*out*/;
            resourceInputs["originURL"] = undefined /*out*/;
            resourceInputs["resourceGroupName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Website.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Website resource.
 */
export interface WebsiteArgs {
    cdn?: pulumi.Input<boolean | inputs.WebsiteCDNConfigArgs>;
    /**
     * The domain configuration of the website.
     */
    domain?: pulumi.Input<inputs.WebsiteDomainConfigArgs>;
    /**
     * The default error page for the website. Defaults to error.html.
     */
    errorDoc?: pulumi.Input<string>;
    /**
     * The default document for the site. Defaults to index.html.
     */
    indexDoc?: pulumi.Input<string>;
    /**
     * The root directory containing contents of the built website contents.
     */
    sitePath: pulumi.Input<string>;
    /**
     * The storage configuration of the website.
     */
    storage?: pulumi.Input<inputs.WebsiteStorageConfigArgs>;
}
